version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    depends_on:
      - app

  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path /var/www/certbot --email fernandotzoc4@gmail.com --agree-tos -d fernandotzoc.dev
    volumes:
      - ./certbot/www:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
