version: '3'
services:
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'
  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app