version: '3'

services:
  app:
    build: .
    restart: always
    ports:
      - '3000:3000'

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx:/etc/nginx
    depends_on:
      - app

  certbot:
    image: certbot/certbot
    restart: always
    volumes:
      - ./nginx/certs:/etc/letsencrypt
    command: certonly --webroot --email fernandotzoc4@gmail.com --agree-tos --no-eff-email -d fernandotzoc.dev
